services:
  db:
    image: postgres:18
    user: root
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=postgres
    restart: always             # run as a service
    volumes:
        - ${PGDB_VOLUME}:/var/lib/postgresql/18/docker      # Important Change: the PGDATA environment variable of the image was changed to be version specific in PostgreSQL 18 and above‚Å†

  odoo:
    image: odoo:19
    user: root
    depends_on:
      - db
    expose:
      - "8069"
      - "8072" # live chat
    tty: true
    command: --
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=${POSTGRES_PASSWORD}
      - PIP_BREAK_SYSTEM_PACKAGES=1
    volumes:
      #- /etc/timezone:/etc/timezone:ro
      #- /etc/localtime:/etc/localtime:ro
#      - ./entrypoint.sh:/entrypoint.sh
      - ./addons:/mnt/extra-addons
      - ./etc:/etc/odoo
    restart: always             # run as a service

  nginx:
    image: nginx:alpine
    depends_on:
      - odoo
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    restart: always

  cloudflared:
    image: cloudflare/cloudflared:latest
    restart: always

    deploy:
      replicas: 3

    command: tunnel --no-autoupdate run --token ${CLOUDFLARED_TOKEN}

    environment:
      - CLOUDFLARED_TOKEN=${CLOUDFLARED_TOKEN}

    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

    networks:
      - default
    
